//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateRouting.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDistributrCommand
    {
        public tblDistributrCommand()
        {
            this.tblRoutingCentres = new HashSet<tblRoutingCentre>();
            this.tblRoutingStatus = new HashSet<tblRoutingStatu>();
        }
    
        public long Id { get; set; }
        public System.Guid CommandId { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<System.Guid> DocumentParentId { get; set; }
        public bool IsRetired { get; set; }
        public System.DateTime DateCommandInserted { get; set; }
        public System.Guid CommandGeneratedByCostCentreApplicationId { get; set; }
        public System.Guid CommandGeneratedByUserId { get; set; }
        public string CommandType { get; set; }
        public string JsonCommand { get; set; }
    
        public virtual ICollection<tblRoutingCentre> tblRoutingCentres { get; set; }
        public virtual ICollection<tblRoutingStatu> tblRoutingStatus { get; set; }
    }
}
