//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MigrateRouting.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoutingStatu
    {
        public long Id { get; set; }
        public long DistributorCommandId { get; set; }
        public System.Guid DestinationCostCentreApplicationId { get; set; }
        public bool Delivered { get; set; }
        public Nullable<System.DateTime> DateDelivered { get; set; }
        public bool Executed { get; set; }
        public Nullable<System.DateTime> DateExecuted { get; set; }
    
        public virtual tblDistributrCommand tblDistributrCommand { get; set; }
    }
}
