//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distributr.Core.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Distributr.Core.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with cte as (
        ///    select distinct  o.Id, 
        ///	o.DocumentDateIssued,
        ///	o.DocumentReference,
        ///	o.SaleDiscount,	
        ///	ISNULL(sum((il.Quantity * il.Value) + (il.Vat * il.Quantity)),0) as InvoiceAmount,
        ///	ISNULL((
        ///		select sum( l.Value) from tblDocument doc join tblLineItems l on l.DocumentID=doc.Id 
        ///		where  doc.DocumentTypeId=8 and doc.InvoiceOrderId=i.Id
        ///		group by doc.InvoiceOrderId		
        ///	) ,0)as ReceiptAmount,
        ///	ISNULL((
        ///		select sum((l.Quantity * l.Value) +(l.Vat * l.Quantity)) CreditAmount  from tblDocumen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainOrderRepositoryOutstandingQuery {
            get {
                return ResourceManager.GetString("MainOrderRepositoryOutstandingQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select top 20 * from tbldocument doc where  doc.DocumentTypeId=1 and doc.OrderOrderTypeId=&apos;1&apos;
        ///and DocumentReference  not in(select ex.DocumentReference  from tblExportImportAudit ex)
        ///union all
        ///select top 20 * from tbldocument doc where  doc.DocumentTypeId=1 and doc.OrderOrderTypeId=&apos;3&apos;
        ///and DocumentReference  not in(select ex.DocumentReference  from tblExportImportAudit ex)
        ///.
        /// </summary>
        internal static string OrdersAndSalesPendingExportQuerySQL {
            get {
                return ResourceManager.GetString("OrdersAndSalesPendingExportQuerySQL", resourceCulture);
            }
        }
    }
}
