//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class paymentgatewayEntities : DbContext
    {
        public paymentgatewayEntities()
            : base("name=paymentgatewayEntities")
        {
        }
        public paymentgatewayEntities(string con)
            : base(con)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAuditLog> tblAuditLog { get; set; }
        public DbSet<tblClient> tblClient { get; set; }
        public DbSet<tblClientMember> tblClientMember { get; set; }
        public DbSet<tblFarmers> tblFarmers { get; set; }
        public DbSet<tblPaymentRequest> tblPaymentRequest { get; set; }
        public DbSet<tblPaymentResponse> tblPaymentResponse { get; set; }
        public DbSet<tblRequest> tblRequest { get; set; }
        public DbSet<tblRequestResponce> tblRequestResponce { get; set; }
        public DbSet<tblRequestResponceDestination> tblRequestResponceDestination { get; set; }
        public DbSet<tblServiceProvider> tblServiceProvider { get; set; }
        public DbSet<tblSms> tblSms { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
    }
}
