//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuditLog
    {
        public System.Guid Id { get; set; }
        public System.Guid DistributorCostCenterId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Type { get; set; }
        public string Direction { get; set; }
        public string Description { get; set; }
        public Nullable<int> Module { get; set; }
    }
}
