//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientMember
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int MemberType { get; set; }
        public int ClientId { get; set; }
        public string ExternalId { get; set; }
        public System.DateTime IM_DateCreated { get; set; }
        public System.DateTime IM_DateLastUpdated { get; set; }
        public int IM_Status { get; set; }
    
        public virtual tblClient tblClient { get; set; }
    }
}
