//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFarmers
    {
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string FactoryCode { get; set; }
        public System.Guid FactoryId { get; set; }
        public string FactoryUrl { get; set; }
        public System.DateTime IM_DateCreated { get; set; }
        public System.DateTime IM_DateLastUpdated { get; set; }
        public bool IM_Status { get; set; }
    }
}
