//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestResponceDestination
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string ResponseTimeStamp { get; set; }
        public int RequestResponceId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string MessageId { get; set; }
        public string StatusCode { get; set; }
        public string StatusDetails { get; set; }
    
        public virtual tblRequestResponce tblRequestResponce { get; set; }
    }
}
