//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSms
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DistributorCostCenterId { get; set; }
        public string TransactionRefId { get; set; }
        public Nullable<int> ClientRequestResponseType { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public string Recipients { get; set; }
        public string SMSBody { get; set; }
        public string SmsStatus { get; set; }
        public string SdpRequestId { get; set; }
        public string SdpDestinationResponses { get; set; }
        public string SdpVersion { get; set; }
        public string SdpStatusCode { get; set; }
        public string SdpStatusString { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
    }
}
