//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentGateway.WSApi.Lib.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string Password { get; set; }
        public bool HasChangePassword { get; set; }
        public System.DateTime IM_DateCreated { get; set; }
        public System.DateTime IM_DateUpdated { get; set; }
        public bool IM_IsActive { get; set; }
    }
}
