#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mobile.Common.Resource", IsApplication=false)]

namespace Mobile.Common
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public static int color_accent = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int color_accent_dark = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public static int color_action = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public static int color_action_bar_content = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public static int color_action_bar_content_30_opacity = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public static int color_action_pressed = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public static int color_action_shadow = 2130968590;
			
			// aapt resource value: 0x7f040006
			public static int color_alternate_action = 2130968582;
			
			// aapt resource value: 0x7f040002
			public static int color_background = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int color_background_dark = 2130968579;
			
			// aapt resource value: 0x7f040000
			public static int color_primary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int color_primary_dark = 2130968577;
			
			// aapt resource value: 0x7f040008
			public static int color_primary_text = 2130968584;
			
			// aapt resource value: 0x7f040011
			public static int color_receive_payment_confirmed = 2130968593;
			
			// aapt resource value: 0x7f040009
			public static int color_secondary_text = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public static int color_side_panel = 2130968591;
			
			// aapt resource value: 0x7f040010
			public static int color_side_panel_darker = 2130968592;
			
			// aapt resource value: 0x7f040007
			public static int transparent = 2130968583;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020004
			public static int color_alternate_action = 2130837508;
			
			// aapt resource value: 0x7f020000
			public static int ic_action_hamburger = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_action_left_arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int ic_search = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int search_widget_background = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public static int drawer_layout = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public static int fab_overlay = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public static int fab_overlay_content = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public static int fabbutton = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public static int fragment_container = 2131165195;
			
			// aapt resource value: 0x7f070000
			public static int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public static int popup_view = 2131165199;
			
			// aapt resource value: 0x7f070008
			public static int screen_header = 2131165192;
			
			// aapt resource value: 0x7f070009
			public static int screen_header_content = 2131165193;
			
			// aapt resource value: 0x7f070011
			public static int search_widget = 2131165201;
			
			// aapt resource value: 0x7f070010
			public static int side_panel_fragment = 2131165200;
			
			// aapt resource value: 0x7f070001
			public static int summary = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int summary_scroll = 2131165186;
			
			// aapt resource value: 0x7f070003
			public static int summary_text = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public static int tab_host = 2131165194;
			
			// aapt resource value: 0x7f070004
			public static int technical = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int technical_scroll = 2131165189;
			
			// aapt resource value: 0x7f070006
			public static int technical_text = 2131165190;
			
			// aapt resource value: 0x7f070012
			public static int toolbar = 2131165202;
			
			// aapt resource value: 0x7f070013
			public static int toolbar_title = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int error_alert = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int fragment_host_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int search_widget = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int tab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int tab_host = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int toolbar = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public static int back = 2131034115;
			
			// aapt resource value: 0x7f050005
			public static int close = 2131034117;
			
			// aapt resource value: 0x7f050001
			public static int default_technical_info_text = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int error_alert_title = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int open = 2131034116;
			
			// aapt resource value: 0x7f050006
			public static int search = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public static int AppTheme_AlertDialog = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
