using System;

namespace Distributr.WPF.Lib.Services.Payment.Request
{
    public class AsynchronousPaymentQueryRequest : ClientRequestResponseBase
    {
        /// <summary>
        /// use base class TransactionRefId for this requsts internalTransactionId
        /// </summary>
        public Guid ApplicationId { get; set; }// //unique identifier generated by the SDP when provisioning an app



      
    }
}
