//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distributr.WSAPI.Lib.Services.SyncResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyncResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Distributr.WSAPI.Lib.Services.SyncResources.SyncResource", typeof(SyncResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select con.id from tblCostCentre cc
        ///right join tblContact  con on cc.id=con.CostCenterId
        ///where  (cc.id=&apos;{0}&apos; or cc.ParentCostCentreId=&apos;{0}&apos;)
        ///.
        /// </summary>
        internal static string DHubContact {
            get {
                return ResourceManager.GetString("DHubContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @costcentreid uniqueidentifier ;
        ///set @costcentreid=&apos;{0}&apos;;
        ///declare @from datetime ;
        ///set @from=&apos;{1}&apos;;
        ///select p.[Id] as MasterId
        ///    ,p.[DiscountGroup] as DiscountGroupMasterId
        ///    ,p.[IM_DateCreated] as DateCreated
        ///    ,p.[IM_DateLastUpdated] as DateLastUpdated
        ///    ,p.[IM_Status]  as StatusId 
        ///    ,p.id as LineItemId
        ///	,p.quantity as Quantity
        ///    ,p.DiscountRate as DiscountRate
        ///    ,p.EffectiveDate as EffectiveDate
        ///    ,p.EndDate as EndDate
        ///    ,p.ProductRef as ProductMasterId
        /// from  tbl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DHubGroupProdcutDiscount {
            get {
                return ResourceManager.GetString("DHubGroupProdcutDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select inv.id from tblCostCentre cc
        /// join tblInventory  inv on cc.id=inv.WareHouseId
        /// join tblProduct p on p.id=inv.ProductId
        ///where  (cc.id=&apos;{0}&apos; or cc.ParentCostCentreId=&apos;{0}&apos;)
        ///and p.IM_Status=1.
        /// </summary>
        internal static string DHubInventory {
            get {
                return ResourceManager.GetString("DHubInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select cc.id from tblCostCentre cc
        ///where cc.CostCentreType=5
        ///and (cc.id=&apos;{0}&apos; or cc.ParentCostCentreId=&apos;{0}&apos;).
        /// </summary>
        internal static string DHubOutlet {
            get {
                return ResourceManager.GetString("DHubOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select ovd.id from tblCostCentre cc
        ///right join tblOutletVisitDay ovd on ovd.OutletId=cc.Id
        ///where cc.CostCentreType=5
        ///and (cc.id=&apos;{0}&apos; or cc.ParentCostCentreId=&apos;{0}&apos;).
        /// </summary>
        internal static string DHubOutletVisit {
            get {
                return ResourceManager.GetString("DHubOutletVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DHubPayments {
            get {
                return ResourceManager.GetString("DHubPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select u.id from tblCostCentre cc
        ///right join tblUsers  u on cc.id=u.CostCenterId
        ///where  (cc.id=&apos;{0}&apos; or cc.ParentCostCentreId=&apos;{0}&apos;)
        ///.
        /// </summary>
        internal static string DHubUsers {
            get {
                return ResourceManager.GetString("DHubUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @costcentreid uniqueidentifier ;
        ///set @costcentreid=&apos;{0}&apos;;
        ///declare @otherypeid int ;
        ///set @otherypeid=&apos;{1}&apos;;
        ///if(@otherypeid=0)
        ///	begin
        ///		select u.id from tblCostCentre cc
        ///		right join tblUsers  u on cc.id=u.CostCenterId
        ///		where  cc.id=@costcentreid
        ///	end
        ///else if(@otherypeid=1)
        ///	begin
        ///		select u.id from tblCostCentre cc
        ///		right join tblUsers  u on cc.id=u.CostCenterId
        ///		where  cc.id=@costcentreid
        ///		union all
        ///		select u.id from tblUsers u	
        ///	   join tblCostCentre cc on cc.Id=u.CostCenterId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MobileUsers {
            get {
                return ResourceManager.GetString("MobileUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select con.id from tblSalemanRoute sr
        ///right join tblCostCentre cc on sr.RouteId=cc.RouteId
        ///right join tblContact  con on cc.id=con.CostCenterId
        ///where  sr.SalemanId=&apos;{0}&apos;.
        /// </summary>
        internal static string SalesmanContact {
            get {
                return ResourceManager.GetString("SalesmanContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select distinct cc.id,cc.Name from tblSalemanRoute sr
        ///right join tblCostCentre cc on sr.RouteId=cc.RouteId
        ///where sr.SalemanId=&apos;{0}&apos;.
        /// </summary>
        internal static string SalesmanOutlet {
            get {
                return ResourceManager.GetString("SalesmanOutlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t.id
        ///  FROM [dbo].[tblTarget] t
        ///  left join tblCostCentre cc on cc.id=t.CostCentreId
        ///  where cc.ParentCostCentreId=&apos;{0}&apos;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
