// <auto-generated />
namespace Integration.QuickBooks.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddReceiptLocalItemandReceiptLineItemLocal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReceiptLocalItemandReceiptLineItemLocal));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091424483_AddReceiptLocalItemandReceiptLineItemLocal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
