// <auto-generated />
namespace Integration.QuickBooks.Lib.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddOutletInvoiceAndLineItemsLocalImport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOutletInvoiceAndLineItemsLocalImport));
        
        string IMigrationMetadata.Id
        {
            get { return "201409090618558_AddOutletInvoiceAndLineItemsLocalImport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
