using System;

namespace PaymentGateway.WSApi.Lib.Domain.Payments.Client.Request
{
    public class PaymentQueryRequest : ClientRequestResponseBase
    {
        /// <summary>
        /// use base class TransactionRefId for this requsts internalTransactionId
        /// </summary>
        public Guid ApplicationId { get; set; }// //unique identifier generated by the SDP when provisioning an app
    }
}
