update 	tblArea	 set IM_Status=2 where IM_Status=3
update 	tblAsset	 set IM_Status=2 where IM_Status=3
update 	tblAssetCategory	 set IM_Status=2 where IM_Status=3
update 	tblAssetStatus	 set IM_Status=2 where IM_Status=3
update 	tblAssetType	 set IM_Status=2 where IM_Status=3
update 	tblBank	 set IM_Status=2 where IM_Status=3
update 	tblBankBranch	 set IM_Status=2 where IM_Status=3
update 	tblCentre	 set IM_Status=2 where IM_Status=3
update 	tblCentreType	 set IM_Status=2 where IM_Status=3
update 	tblCertainValueCertainProductDiscount	 set IM_Status=2 where IM_Status=3
update 	tblCertainValueCertainProductDiscountItem	 set IM_Status=2 where IM_Status=3
update 	tblChannelPackaging	 set IM_Status=2 where IM_Status=3
update 	tblClientMasterDataTracker	 set IM_Status=2 where IM_Status=3
update 	tblCommodity	 set IM_Status=2 where IM_Status=3
update 	tblCommodityGrade	 set IM_Status=2 where IM_Status=3
update 	tblCommodityOwner	 set IM_Status=2 where IM_Status=3
update 	tblCommodityOwnerType	 set IM_Status=2 where IM_Status=3
update 	tblCommodityProducer	 set IM_Status=2 where IM_Status=3
update 	tblCommodityType	 set IM_Status=2 where IM_Status=3
update 	tblCompetitor	 set IM_Status=2 where IM_Status=3
update 	tblCompetitorProducts	 set IM_Status=2 where IM_Status=3
update 	tblContact	 set IM_Status=2 where IM_Status=3
update 	tblContactType	 set IM_Status=2 where IM_Status=3
update 	tblContainment	 set IM_Status=2 where IM_Status=3
update 	tblCostCentre	 set IM_Status=2 where IM_Status=3
update 	tblCostCentreApplication	 set IM_Status=2 where IM_Status=3
update 	tblCountry	 set IM_Status=2 where IM_Status=3
update 	tblCustomerDiscount	 set IM_Status=2 where IM_Status=3
update 	tblCustomerDiscountItem	 set IM_Status=2 where IM_Status=3
update 	tblDiscountGroup	 set IM_Status=2 where IM_Status=3
update 	tblDiscountItem	 set IM_Status=2 where IM_Status=3
update 	tblDiscounts	 set IM_Status=2 where IM_Status=3
update 	tblDistrict	 set IM_Status=2 where IM_Status=3
update 	tblFiles	 set IM_Status=2 where IM_Status=3
update 	tblFreeOfChargeDiscount	 set IM_Status=2 where IM_Status=3
update 	tblInventory	 set IM_Status=2 where IM_Status=3
update 	tblInventorySerials	 set IM_Status=2 where IM_Status=3
update 	tblInventoryTransaction	 set IM_Status=2 where IM_Status=3
update 	tblMaritalStatus	 set IM_Status=2 where IM_Status=3
update 	tblMarketAudit	 set IM_Status=2 where IM_Status=3
update 	tblOutletAudit	 set IM_Status=2 where IM_Status=3
update 	tblOutletCategory	 set IM_Status=2 where IM_Status=3
update 	tblOutletPriority	 set IM_Status=2 where IM_Status=3
update 	tblOutletType	 set IM_Status=2 where IM_Status=3
update 	tblOutletVisitDay	 set IM_Status=2 where IM_Status=3
update 	tblPricing	 set IM_Status=2 where IM_Status=3
update 	tblPricingItem	 set IM_Status=2 where IM_Status=3
update 	tblPricingTier	 set IM_Status=2 where IM_Status=3
update 	tblProduct	 set IM_Status=2 where IM_Status=3
update 	tblProductBrand	 set IM_Status=2 where IM_Status=3
update 	tblProductDiscountGroup	 set IM_Status=2 where IM_Status=3
update 	tblProductDiscountGroupItem	 set IM_Status=2 where IM_Status=3
update 	tblProductFlavour	 set IM_Status=2 where IM_Status=3
update 	tblProductPackaging	 set IM_Status=2 where IM_Status=3
update 	tblProductPackagingType	 set IM_Status=2 where IM_Status=3
update 	tblProductType	 set IM_Status=2 where IM_Status=3
update 	tblPromotionDiscount	 set IM_Status=2 where IM_Status=3
update 	tblPromotionDiscountItem	 set IM_Status=2 where IM_Status=3
update 	tblProvince	 set IM_Status=2 where IM_Status=3
update 	tblPurchasingClerkRoute	 set IM_Status=2 where IM_Status=3
update 	tblRegion	 set IM_Status=2 where IM_Status=3
update 	tblReOrderLevel	 set IM_Status=2 where IM_Status=3
update 	tblRetireDocumentsetting	 set IM_Status=2 where IM_Status=3
update 	tblRoutes	 set IM_Status=2 where IM_Status=3
update 	tblSalemanRoute	 set IM_Status=2 where IM_Status=3
update 	tblSaleValueDiscount	 set IM_Status=2 where IM_Status=3
update 	tblSaleValueDiscountItems	 set IM_Status=2 where IM_Status=3
update 	tblsettings	 set IM_Status=2 where IM_Status=3
update 	tblSocioEconomicStatus	 set IM_Status=2 where IM_Status=3
update 	tblSupplier	 set IM_Status=2 where IM_Status=3
update 	tblTarget	 set IM_Status=2 where IM_Status=3
update 	tblTargetItem	 set IM_Status=2 where IM_Status=3
update 	tblTargetPeriod	 set IM_Status=2 where IM_Status=3
update 	tblTerritory	 set IM_Status=2 where IM_Status=3
update 	tblUserGroup	 set IM_Status=2 where IM_Status=3
update 	tblUserGroupRoles	 set IM_Status=2 where IM_Status=3
update 	tblUsers	 set IM_Status=2 where IM_Status=3
update 	tblUserTypes	 set IM_Status=2 where IM_Status=3
update 	tblVATClass	 set IM_Status=2 where IM_Status=3
update 	tblVATClassItem	 set IM_Status=2 where IM_Status=3
update 	test	 set IM_Status=2 where IM_Status=3
GO